language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - git fetch --unshallow
  - version="$(git describe --long --tags | sed 's/^v//;s/-\([0-9]\+\)-g\([0-9a-f]\+\)/+\1.\2/')"
  - sed -i 's/versionName .*/versionName "'"${version}"'"/' app/build.gradle
  - grep 'versionName' app/build.gradle
  - cp signing.properties.travis signing.properties

after_success:
  - cp app/build/outputs/apk/app-release.apk "douya-ci-${version}.apk"
  - >-
    description="$(git show -s --format='> Commit: %H%n> Author: %an%n> Date: %ad%n%n%s%+b')"
  - ./upload-to-releases.sh 'DreaminginCodeZH/DouyaCiBuilds' "${version}" "${description}" "douya-ci-${version}.apk"

after_failure:
  - cat app/build/outputs/lint-results-*.html
